services:
  test_db:
    image: postgres:15-alpine
    container_name: github_notifier_test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - '5434:5432'

  test_redis:
    image: redis:7-alpine
    container_name: github_notifier_test_redis
    ports:
      - '6380:6379'
  test_smtp:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: github_notifier_test_smtp
    ports:
      - '1025:1025'

  test_scanner:
    profiles:
      - e2e
    build:
      context: .
      dockerfile: services/github-scanner-service/Dockerfile
    container_name: github_notifier_test_scanner
    environment:
      SCANNER_SERVICE_REST_PORT: 3002
      GITHUB_API_TIMEOUT_MS: 5000
      GH_TOKEN: ${GH_TOKEN:-}
      NODE_ENV: production
    ports:
      - '3002:3002'
