input {
  gelf {
    port => 12201
  }
}

filter {
  json {
    source => "message"
    remove_field => ["message"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "github-notifier-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}
